language: csharp
dotnet: 3.1

env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1

os: linux

jobs:
  include:
    - dist: bionic
    - dist: xenial

script:
    - dotnet build test1/test1.sln -c Release
    - dotnet test -c Release --no-build test/test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
