language: csharp
solution: test1/test1.sln

jobs:
  include:
    - dotnet: 3.1.402
      mono: none
    - mono: latest

os: linux

install:
  - nuget install xunit.runners -Version 2.4.0 -OutputDirectory testrunner
  
script: 
    - msbuild /p:Configuration=Release test1/test1.sln
    - mono ./testrunner/xunit.runners.2.4.0/tools/xunit.console.clr4.exe .test/test.sln