language: csharp

dotnet: 2.1.4

env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1

os: 
   - windows
   - linux

jobs:
  include:
    - dist: bionic
    - dist: xenial

script:
    - dotnet build CIDemo.sln -c Release
    - dotnet test -c Release --no-build test/test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
