language: csharp
dotnet: 3.1

os: linux

install:
  - nuget restore test1/test1.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
  
script: 
    - msbuild /p:Configuration=Release test1/test1.sln
    - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe .test/test.sln